---
- hosts: dmgr
  vars_files:
    - ../vars/{{env}}/main.yml
  tasks:
    - name: unpack tarball
      unarchive:
        src: /opt/IBM/software/C1G32ML.tar.gz
        dest: /opt/IBM/software/
        copy: no
    - name: Copy the response file
      template: src=templates/responsefile.nd.txt dest=/opt/IBM/responsefile.nd.txt
    - name: Install the deployment manager
      shell: '/opt/IBM/software/WAS/install -options /opt/IBM/responsefile.nd.txt -silent'
    - name: Create the deployment manager profile
      shell: '/opt/IBM/WebSphere/AppServer/bin/manageprofiles.sh -create -templatePath /opt/IBM/WebSphere/AppServer/profileTemplates/management/ -hostname {{inventory_hostname}} -nodeName {{dmgrNode}} -cellName {{dmgrCell}} -profileName Dmgr01 -profilePath /opt/IBM/WebSphere/AppServer/profiles/Dmgr01 -enableAdminSecurity true -adminUserName {{adminuser}} -adminPassword {{adminpassword}}'
    - name: Stop the deployment manager
      shell: '/opt/IBM/WebSphere/AppServer/profiles/Dmgr01/bin/stopManager.sh -user {{adminuser}} -password {{adminpassword}}'
      ignore_errors: yes
    - name: Start the deployment manager
      shell: '/opt/IBM/WebSphere/AppServer/profiles/Dmgr01/bin/startManager.sh -user {{adminuser}} -password {{adminpassword}}'

