---
- hosts: dmgr
  vars_files:
    - ../vars/{{env}}/main.yml
  tasks:
    - name: Stop the deployment manager
      shell: '/opt/IBM/WebSphere/AppServer/profiles/Dmgr01/bin/stopManager.sh -user {{adminuser}} -password {{adminpassword}}'
      ignore_errors: yes
    - name: Uninstall IBM Installation Manager
      shell: '/opt/IBM/WebSphere/AppServer/uninstall/uninstall -silent'
      ignore_errors: yes
    - name: Remove directories
      shell: 'rm -rf /opt/IBM/WebSphere/'
      ignore_errors: yes

